Be-5 CRUD, logging added.
Blassel228/InternshipAtGrimaliuk- pull request #5
Opened 2023-10-20 17:28 UTC by Blassel228

Finally, sublime additions to my big-ass project.
І так, я намагався додати щось щоб воно хендлело помилки, вроді би вийшло. Все іше я думаю і так видно.

2023-10-20 20:56 UTC, andriiko489 requested changes
Small fixes, main task completed. https://www.youtube.com/watch?v=8Im74b55vFc

2023-10-20 20:56 UTC, andriiko489 commented on routers/user.py
Роути зміни як я писав в тг

2023-10-20 20:56 UTC, andriiko489 commented on requirements.txt
додай pydantic[email], passlib, bcrypt

2023-10-21 07:52 UTC, Blassel228 commented
Забув добавиити декілька інітів в перший коміт, тому вийшло два, вроді два коміти можна з'єднати в один, але я поспішив і залив два окремі.

2023-11-12 09:47 UTC, andriiko489 approved these changes
Гарна структура, всьо добре. Єдине - що я пропустив чомусь під час попередніх ревью - додай папку .idea в gitignore

2023-11-12 11:02 UTC, merged